### PR TITLE
Milestone five

### PR DESCRIPTION
**Pull request by andresporras3423**
- created model for friendship
- friendship belongs to two users identified by user_id and friend_id 
- user has many created invitations and many pending invitations received
- add methods in user to get friends and pending invitations

### CODE REVIEW

**Comment by samgaco** [comment]
Hi @andresporras3423 and @Salvador-ON :high_brightness: 

Please, verify your app complies the following points, right now a user can not request a friendship to other users.

- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))  
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))  
- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

Work on those and submit back once you are done :+1: 

-------------------

* ###### STATUS OF THE MILESTONE: REQUESTED CHANGES :stop_sign:

**Comment by andresporras3423** [comment]
- the user can see and accept or reject invitations
- the user can post, can comment and like post
- the user can invite friends
- in timeline the user can see his post and the posts of their friends

**Review by nikasulo — APPROVED** [review]
# Great work! @andresporras3423 and @Salvador-ON :medal_military: 
You have done a beautiful job building this! Please merge and keep moving forward :+1: I wish you the very best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by andresporras3423** [comment]
Thanks

**Pull request merged**
